server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: config-server-route
          uri: lb://CONFIG-SERVER
          predicates:
            - Path=/config/**
        - id: client-route
          uri: lb://MY-CLIENT
          predicates:
            - Path=/client/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true