server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    gateway:
      routes:
        - id: config-server-route
          uri: lb://CONFIG-SERVER
          predicates:
            - Path=/config/**
        - id: client-route
          uri: lb://MY-CLIENT
          predicates:
            - Path=/client/**

datasource:
  uri: jdbc:mysql://localhost:3306/user_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  